baseURL: "https://aardvark922.github.io"
title: Jieqiong Jin
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 1
        - name: Teaching
          url: courses/
          weight: 2
        - name: About Me
          url: about/
          weight: 3 
##        - name: Newsletter
##          url: https://pmichaillat.substack.com
#          weight: 4

params:
    description: "I am a sixth year Ph.D. student in Economics at Purdue University."
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jieqiong(Cicy) Jin
          subtitle: "Welcome to my personal website! I'm Jieqiong Jin (金洁琼), a Ph.D. candidate in economics at Purdue University. 
          <br> My current research focuses on Experimental and Behavioral Economics, Public Economics and Applied Microeconomics.
          <b>I am on the 2023-2024 job market.<b>"
          imageUrl: "Jieqiong_Jin_2019_crop.jpg"
          imageWidth: 250
          imageHeight: 250
          imageTitle: Jieqiong Jin
          buttons:
            - name: Research
              url: papers/
            - name: Teaching
              url: courses/
            - name: About Me
              url: about/
#            - name: Newsletter
#              url: https://pmichaillat.substack.com
#            - name: Tags
#              url: tags/
#            - name: Archive
#              url: archive/
    socialIcons:
        - name: CV
          url: cv_231011.pdf
        - name: Email
          url: mailto:jin334@purdue.edu
        - name: Location
          url: location/
#        - name: Office Hours
#          url: officehours/
#        - name: Google Scholar
#          url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
#        - name: YouTube
#          url: https://www.youtube.com/@pmichaillat
        - name: GitHub
          url: https://github.com/aardvark922
#        - name: Substack
#          url: https://pmichaillat.substack.com
#        - name: Twitter
#          url: https://twitter.com/pmichaillat

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jieqiong(Cicy) Jin"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
